### ISSUE TITLE
message reject semantics around errors (error handling policy)

### ISSUE THREAD

**Issue by mattcamuto** [wanelo/lapine#1]
We should look at error handling semantics in the consumer (runner) as right now we are blindly acknowledging any messages that are consumed (I think) If we encounter an error we should reject the message, which will re-enqueue it in rabbit. Later on we can revisit proper dead letter q and also retry semantics (count etc). But right now I think we blindly report exceptions to new_relic but always ack the message.

**Comment by sax** [comment]
We need to think about this before implementing anything. How about we use this issue as a sounding board?

Issues:

* Multiple classes can subscribe to messages, but errors can happen in only a subset of classes
* RabbitMQ only tracks whether messages are being redelivered, not the count of how many times a message has been rejected

For the last issue, one way of handling this is to reject the message with `requeue: false`, then manually re-enqueue with a counter included in the metadata. Then somehow we'd need to be able to stop things from being re-enqueued after a certain number of retries.

For the first issue, maybe we could do something like the following:

* We set a retry policy on the consumer class
* If a message comes in with a retry count greater then that configured for the class, the dispatcher skips the class

There are a lot of potential problems with this solution, which we should work out. But there are probably going to be issues with all solutions.

We may also need to set a global retry policy for a queue. Some we may want to fail fast and skip further processing. Some we may want to not retry, but allow all dispatch classes to receive the message.

**Comment by sax** [comment]
I'm going to close this, because people can implement their own message rejection policy using middleware.
